### ISSUE TITLE
error running build-prod

### ISSUE THREAD

**Issue by retorquere** [jobsta/reportbro-designer#50]
When running `npm run build-prod` I end with an error:

```
reportbro-designer/node_modules/uglify-js/tools/node.js:42
    sys.error("WARN: " + txt);
        ^

TypeError: sys.error is not a function
```

**Comment by alhman** [comment]
Did you run `npm install` before?
on what machine are you building? there seems to be some major configuration issue when sys.error is missing on your system.

**Comment by retorquere** [comment]
Sys.error has been deprecated in newer node versions

**Comment by alhman** [comment]
but was it removed or just deprecated?
maybe using a newer webpack version will solve this.

**Comment by retorquere** [comment]
https://nodejs.org/api/deprecations.html#DEP0025

I see talk of `sys` being replaced with `util` (and thus going away) going back to 2012. I reckon I could make webpack replace `sys` with `util` but it's a bit of a hack.

**Comment by retorquere** [comment]
(I did run `npm install` first, sorry)

**Comment by alhman** [comment]
you could try using a newer webpack version as our used version 2.4.1 is quite old.

**Comment by retorquere** [comment]
That demands webpack-cli to be installed, and it asks me whether it should do it for me, but if I say yes I get

```
$ npm run build-prod

> reportbro-designer@1.5.2 build-prod /Users/emile/github/reportbro-designer
> webpack --config webpack.config.prod.js && uglifyjs ./dist/reportbro.js --comments '/Copyright/' -c -m -o ./dist/reportbro.min.js --source-map ./dist/reportbro.min.js.map

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> ejs@2.7.4 postinstall /Users/emile/github/reportbro-designer/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.

+ webpack-cli@4.0.0
added 540 packages from 359 contributors and audited 1299 packages in 21.421s

48 packages are looking for funding
  run `npm fund` for details

found 14 vulnerabilities (6 low, 2 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Error: Cannot find module 'webpack-cli'
Require stack:
- /Users/emile/github/reportbro-designer/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at /Users/emile/github/reportbro-designer/node_modules/webpack/bin/webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/emile/github/reportbro-designer/node_modules/webpack/bin/webpack.js'
  ]
}
```

what version of node will the current master work on? It's not just webpack that's old, babel must be updated too, and there's a fair few audit messages besides that.
